"""add avatar_url to users

Revision ID: eadc6f7ce6af
Revises: 0001
Create Date: 2026-05-15 00:35:09.105192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eadc6f7ce6af'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    op.alter_column('tips', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.create_index(op.f('ix_tips_id'), 'tips', ['id'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_tips_id'), table_name='tips')
    op.alter_column('tips', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    # ### end Alembic commands ###
